---
- name: Download and import Kubernetes GPG key # noqa command-instead-of-module
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /bin/bash
  args:
    creates: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
  changed_when: true

- name: Add the k8s apt repository
  become: true
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'

- name: Update apt package index with the new repository
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install k8s packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - kubelet
    - kubeadm
    - kubectl
...
